// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence.Database;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251020120849_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Application")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.ChoreInstances.ChoreInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("chore_id");

                    b.Property<DateOnly>("DateDue")
                        .HasColumnType("date")
                        .HasColumnName("date_due");

                    b.PrimitiveCollection<string[]>("ImageLinks")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("image_links");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.HasKey("Id")
                        .HasName("pk_chore_instances");

                    b.HasIndex("ChoreId")
                        .HasDatabaseName("ix_chore_instances_chore_id");

                    b.ToTable("chore_instances", "Application");
                });

            modelBuilder.Entity("Domain.ChoreLists.ChoreList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_chore_lists");

                    b.ToTable("chore_lists", "Application");
                });

            modelBuilder.Entity("Domain.ChoreUsers.ChoreUser", b =>
                {
                    b.Property<Guid>("ChoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("chore_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("ChoreId", "UserId")
                        .HasName("pk_chore_users");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_chore_users_user_id");

                    b.ToTable("chore_users", "Application");
                });

            modelBuilder.Entity("Domain.Chores.Chore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<Guid>("ChoreListId")
                        .HasColumnType("uuid")
                        .HasColumnName("chore_list_id");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer")
                        .HasColumnName("frequency");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_chores");

                    b.HasIndex("ChoreListId")
                        .HasDatabaseName("ix_chores_chore_list_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_chores_user_id");

                    b.ToTable("chores", "Application");
                });

            modelBuilder.Entity("Domain.Comments.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChoreInstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("chore_instance_id");

                    b.Property<Guid?>("ChoreInstanceId1")
                        .HasColumnType("uuid")
                        .HasColumnName("chore_instance_id1");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("EditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_at");

                    b.Property<DateTime>("PublishedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_on");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_comments");

                    b.HasIndex("ChoreInstanceId")
                        .HasDatabaseName("ix_comments_chore_instance_id");

                    b.HasIndex("ChoreInstanceId1")
                        .HasDatabaseName("ix_comments_chore_instance_id1");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_comments_user_id");

                    b.ToTable("comments", "Application");
                });

            modelBuilder.Entity("Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("chore_id");

                    b.Property<DateOnly>("LastKnownPriceDate")
                        .HasColumnType("date")
                        .HasColumnName("last_known_price_date");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("link");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("ChoreId")
                        .HasDatabaseName("ix_products_chore_id");

                    b.ToTable("products", "Application");
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", "Application");
                });

            modelBuilder.Entity("Domain.ChoreInstances.ChoreInstance", b =>
                {
                    b.HasOne("Domain.Chores.Chore", null)
                        .WithMany()
                        .HasForeignKey("ChoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chore_instances_chores_chore_id");
                });

            modelBuilder.Entity("Domain.ChoreUsers.ChoreUser", b =>
                {
                    b.HasOne("Domain.Chores.Chore", null)
                        .WithMany()
                        .HasForeignKey("ChoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chore_users_chores_chore_id");

                    b.HasOne("Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chore_users_users_user_id");
                });

            modelBuilder.Entity("Domain.Chores.Chore", b =>
                {
                    b.HasOne("Domain.ChoreLists.ChoreList", null)
                        .WithMany()
                        .HasForeignKey("ChoreListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chores_chore_lists_chore_list_id");

                    b.HasOne("Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chores_users_user_id");
                });

            modelBuilder.Entity("Domain.Comments.Comment", b =>
                {
                    b.HasOne("Domain.ChoreInstances.ChoreInstance", null)
                        .WithMany()
                        .HasForeignKey("ChoreInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comments_chore_instances_chore_instance_id");

                    b.HasOne("Domain.ChoreInstances.ChoreInstance", null)
                        .WithMany("Comments")
                        .HasForeignKey("ChoreInstanceId1")
                        .HasConstraintName("fk_comments_chore_instances_chore_instance_id1");

                    b.HasOne("Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comments_users_user_id");
                });

            modelBuilder.Entity("Domain.Products.Product", b =>
                {
                    b.HasOne("Domain.Chores.Chore", null)
                        .WithMany("Products")
                        .HasForeignKey("ChoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_products_chores_chore_id");

                    b.OwnsOne("Shared.Price", "LastKnownPrice", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("last_known_price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("last_known_price_currency");

                            b1.HasKey("ProductId");

                            b1.ToTable("products", "Application");

                            b1.WithOwner()
                                .HasForeignKey("ProductId")
                                .HasConstraintName("fk_products_products_id");
                        });

                    b.Navigation("LastKnownPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.ChoreInstances.ChoreInstance", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Domain.Chores.Chore", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
